#!/usr/bin/env bash
# shellcheck shell=bash
#
# Immutable snapshot upload, verification, and commit.
#
# The specification asks for `rclone sync /root/work_data gdrive:backups/latest`.
# That is replaced here, deliberately, and the reason is the most important
# design decision in the runner:
#
#   `sync` makes the destination match the source *including deletions*. The
#   destination is the only durable copy of the state. So a source tree that has
#   lost files — a bad restore, a workload that truncated its own data store, a
#   disk problem — propagates that loss straight into the backup, and then into
#   the next node's restore, and then it is gone. `sync` to a single mutable
#   path converts every failure mode of the workload into permanent data loss.
#
# Instead: every cycle writes a new immutable `snapshots/<utc-timestamp>/`
# directory with `rclone copy` (additive, no deletions ever), verifies it, and
# only then publishes a commit record naming it. The predecessor's snapshot
# remains the fallback until the successor has acknowledged the new one.

readonly SNAPSHOT_TS="${SNAPSHOT_TS:-$(date -u '+%Y%m%dT%H%M%SZ')}"
readonly SNAPSHOT_PATH="${SNAPSHOT_ROOT}/${SNAPSHOT_TS}"

# Publish the snapshot and its commit record. Echoes the snapshot path.
backup_publish() {
  local predecessor="${1:-}"

  [[ -d "$WORK_DIR" ]] || die "backup: ${WORK_DIR} does not exist"

  log "building content manifest for ${WORK_DIR}"
  local manifest="${PIPE_DIR}/MANIFEST.sha256"
  local file_count
  file_count=$(manifest_write "$WORK_DIR" "$manifest")

  local digest
  digest=$(manifest_digest "$manifest")
  log "manifest: ${file_count} file(s), sha256 ${digest:0:16}..."

  # The manifest is uploaded into the snapshot so that the successor can verify
  # what it restored, using hashes the predecessor computed while the workload
  # was frozen. A manifest generated by the consumer only proves the consumer
  # received something self-consistent; this one proves it received *this tree*.
  retry 3 rclone copyto "$manifest" "${DRIVE_REMOTE}:${SNAPSHOT_PATH}/MANIFEST.sha256" \
    || die "could not upload the manifest"

  log "uploading snapshot to ${SNAPSHOT_PATH} (additive copy, no deletions)"
  retry 3 rclone copy "$WORK_DIR" "${DRIVE_REMOTE}:${SNAPSHOT_PATH}" \
    --transfers 8 --checkers 16 --fast-list \
    --exclude '/MANIFEST.sha256' \
    || die "snapshot upload failed"

  log "verifying the uploaded snapshot against the source tree"
  if ! retry 2 rclone check "$WORK_DIR" "${DRIVE_REMOTE}:${SNAPSHOT_PATH}" \
      --one-way --checkers 16 --exclude '/MANIFEST.sha256'; then
    # Deliberately fatal, and deliberately *without* writing a commit record:
    # no commit record means the successor restores the predecessor's snapshot
    # instead of this one, which is exactly the correct fail-safe. Publishing a
    # commit for an unverified snapshot would be worse than losing the cycle.
    die "uploaded snapshot does not match the source tree; no commit record written"
  fi
  log "upload verified"

  local stats files bytes
  stats=$(manifest_stats "$WORK_DIR")
  files=$(printf '%s' "$stats" | awk '{print $1}')
  bytes=$(printf '%s' "$stats" | awk '{print $2}')

  local record
  record=$(jq -n \
    --arg snapshot "$SNAPSHOT_PATH" \
    --arg ts "$SNAPSHOT_TS" \
    --arg parent "$predecessor" \
    --arg manifest_sha256 "$digest" \
    --arg slot "${SLOT:-?}" \
    --arg reason "${NODE_REASON:-cycle}" \
    --argjson files "${files:-0}" \
    --argjson bytes "${bytes:-0}" \
    --argjson run_id "${GITHUB_RUN_ID:-0}" \
    --argjson created_unix "$(now_unix)" \
    '{snapshot:$snapshot, ts:$ts, parent:$parent, manifest_sha256:$manifest_sha256,
      slot:$slot, reason:$reason, files:$files, bytes:$bytes,
      run_id:$run_id, created_unix:$created_unix}')

  printf '%s' "$record" >"${PIPE_DIR}/commit.json"
  retry 3 rclone copyto "${PIPE_DIR}/commit.json" \
    "${DRIVE_REMOTE}:${COMMIT_ROOT}/${SNAPSHOT_TS}.json" \
    || die "could not publish the commit record"

  log "committed snapshot ${SNAPSHOT_PATH} (${files} files, ${bytes} bytes)"
  printf '%s' "$SNAPSHOT_PATH"
}

# Keep the configured rolling window of snapshots.
#
# Runs strictly after the commit record is durable. Pruning first would open a
# window where the newest snapshot exists but nothing points at it, and a crash
# inside that window would strand the successor on an older tree — recoverable,
# but a gratuitously confusing way to lose an hour of work.
backup_prune() {
  local keep="$BACKUP_RETENTION"
  (( keep >= 2 )) || keep=2

  local dirs
  dirs=$(retry 2 rclone lsf --dirs-only "${DRIVE_REMOTE}:${SNAPSHOT_ROOT}/" 2>/dev/null \
    | tr -d '/' | LC_ALL=C sort || true)
  [[ -n "$dirs" ]] || return 0

  local total
  total=$(printf '%s\n' "$dirs" | wc -l | tr -d ' ')
  if (( total <= keep )); then
    log "retention: ${total}/${keep} snapshots present, nothing to prune"
    return 0
  fi

  local doomed
  doomed=$(printf '%s\n' "$dirs" | head -n $((total - keep)))
  local count=0 dir
  while IFS= read -r dir; do
    [[ -n "$dir" ]] || continue
    # Never prune the snapshot this run just committed, whatever the ordering
    # says: a clock skew between two nodes must not be able to delete the
    # current state.
    [[ "$dir" == "$SNAPSHOT_TS" ]] && continue
    if retry 2 rclone purge "${DRIVE_REMOTE}:${SNAPSHOT_ROOT}/${dir}" >/dev/null 2>&1; then
      count=$((count + 1))
    else
      warn "could not prune snapshot ${dir}"
    fi
  done <<<"$doomed"

  log "retention: pruned ${count} snapshot(s), keeping the newest ${keep}"
}
